#! /bin/sh

# Set environment variables
export PATH="$HOME/.config/bspwm/src:$PATH"
export XDG_CURRENT_DESKTOP='bspwm'
## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

#  ╦ ╦╔═╗╦═╗╦╔═╔═╗╔═╗╔═╗╔═╗╔═╗╔═╗
#  ║║║║ ║╠╦╝╠╩╗╚═╗╠═╝╠═╣║  ║╣ ╚═╗
#  ╚╩╝╚═╝╩╚═╩ ╩╚═╝╩  ╩ ╩╚═╝╚═╝╚═╝

pgrep -x sxhkd >/dev/null || sxhkd &

set_screen_layout() {
  if [[ $HOSTNAME == archlinux ]]; then
    xrandr --output HDMI-1 --left-of eDP-1 --auto &
  else
    xrandr --output DP-1 --primary --auto --rotate normal --output DP-3 --auto --rotate right &
  fi
}

two_monitors_workspaces() {
  if [[ $HOSTNAME == archlinux ]]; then
    main_monitor=HDMI-1
    secondary_monitor=eDP-1
    connected=$(xrandr | awk '/ connected/ {count++} END {print count}')
    if [[ $HOSTNAME == archlinux ]]; then
      if [ "$connected" -gt 1 ]; then
        bspc monitor $main_monitor -d '1' '2' '3' '4' '5' '6' '7' '8'
        bspc monitor $secondary_monitor -d '9' '10'
        bspc wm -O "$main_monitor" "$secondary_monitor"
      else
        bspc monitor $secondary_monitor -d '1' '2' '3' '4' '5' '6' '7' '8'
      fi
    fi
  fi
}

# set_screen_layout
two_monitors_workspaces

bspc config external_rules_command "${HOME}"/.config/bspwm/src/ExternalRules

bspc config normal_border_color "#B3BDCB"
bspc config focused_border_color "#80839A"

bspc config top_padding 28
bspc config border_width 0
bspc config window_gap 16

bspc config split_ratio 0.52
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config focus_follows_pointer true
bspc config focus_by_distance true

bspc config presel_feedback_color '#C6A0F6'

bspc rule -a brave desktop=^1 follow=on
bspc rule -a WhatSie desktop=^3 follow=on
bspc rule -a Nemo desktop=^3 follow=on
bspc rule -a com.github.johnfactotum.Foliate desktop=^3 follow=on
bspc rule -a kitty desktop=^4 follow=on
bspc rule -a Postman desktop=^5 follow=on
bspc rule -a DBeaver desktop=^6 follow=on
bspc rule -a Gimp-2.10 desktop=^8 follow=on
bspc rule -a Bitwarden desktop=^8 follow=on
bspc rule -a Slack desktop=^9 follow=on
bspc rule -a io.gitlab.idevecore.Pomodoro desktop=^9 follow=on
bspc rule -a Spotify desktop=^10 follow=on

bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

~/.config/scripts/autostart.sh &
python ~/.config/status_bar_launcher/main.py -p floating-minimal-without-wm &
