#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $HOSTNAME == archlinux ]]; then
  main_monitor=HDMI-1
  secondary_monitor=eDP-1
  bspc monitor $main_monitor -d 1 2 3 4 5 6 7 8 9
  bspc monitor $secondary_monitor -d 10
fi

bspc config normal_border_color         "#B3BDCB"
bspc config focused_border_color        "#80839A"

bspc config top_padding            28
bspc config border_width           0
bspc config window_gap             12

bspc config split_ratio            0.52
bspc config borderless_monocle     false
bspc config gapless_monocle        false
bspc config focus_follows_pointer  true
bspc config focus_by_distance      true

bspc rule -a Zathura state=tiled
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a slack desktop='^10'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Wrapper-2.0 monitor=primary follow=on state=floating border=off rectangle=500x600+0+0

~/.config/scripts/autostart.sh &
python ~/.config/status_bar_launcher/main.py -p floating-minimalistic &
